-- Custom migration: GIN index on articles.search_vector
--
-- This index cannot be generated by Drizzle Kit because Drizzle does not
-- support GIN indexes on generated tsvector columns via the schema DSL.
-- It is defined here as a raw SQL migration that Drizzle's migrator
-- will apply in sequence after the main schema migration.
--
-- CREATE INDEX CONCURRENTLY is not allowed inside a transaction block,
-- so we use CREATE INDEX (without CONCURRENTLY) here.
-- For a live production database with existing data, run this manually
-- with CONCURRENTLY to avoid locking the table.

CREATE INDEX IF NOT EXISTS articles_search_vector_gin_idx
ON articles
USING gin (search_vector);